export const ADD_BLOG='ADD_BLOG';
export const ADD_USER_BLOG='ADD_USER_BLOG';
export const ADD_COMMENT='ADD_COMMENT';
export const ADD_USER_COMMENT='ADD_USER_COMMENT';
export const ADD_NEW_BLOG_FAILED='ADD_NEW_BLOG_FAILED';
export const ADD_COMMENT_FAILED='ADD_COMMENT_FAILED';
